name: Jakarta Rewrite

on:
  workflow_dispatch:
jobs:
  rewrite:
    runs-on: ubuntu-latest
    name: Rewrite to Jakarta
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
          cache: maven
      - name: Configure Git author
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Install JBang
        run: |
          curl -Ls https://sh.jbang.dev | bash -s - app setup
        shell: bash
      - name: Transform sources
        run: |
          export PATH="$HOME/.jbang/bin:$PATH"
          git checkout -b temp-jakarta-rewrite
          ./jakarta/transform.sh
        shell: bash
      - name: Push changes to jakarta-rewrite
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          branch: jakarta-rewrite
